# TODO use JCE
spring:
  datasource:
    url: "jdbc:postgresql://localhost/sdc-yyc-spring"

    username: 'postgres'
    password: 'postgres'
spring.jpa:
  generate-ddl: true

#spring.datasource.url=jdbc:localhost:5432
#spring.datasource.username="postgres"
#spring.datasource.password="postgres"
